server:
  port: 80
  
home:
  person:
    name: father
#    dont know exactly
    age: 44
    likes:
      -smoke
      -tea
      -family
    location:
      country: Uzzbekstain
      area: Taska
  
spring:
  datasource:
    url: jdbc:mysql:///period4?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  thymeleaf:
    #关闭页面缓存
    cache: false